config/routes.rb
Rails.application.routes.draw do
  root to: 'memos#index'
  resources :memos, only: %i[index edit create update destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord
  validates :content, presence: true, length: { in: 1..100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_memo, only: %i[ edit update destroy]
  before_action :set_memos

  def index
    @memo = Memo.new
  end

  def edit
    respond_to do |format|
      flash.now[:notice] = 'コメントの編集中'
      format.html { redirect_to @comment }
      format.js { render :edit }
    end
  end

  def create
    @memo = Memo.new(memo_params)
    respond_to do |format|
      flash.now[:notice] = if @memo.save
                             'メモが作成されました'
                           else
                             'メモの作成に失敗しました'
                           end
      format.js { render :index }
    end
  end

  def update
    respond_to do |format|
      flash.now[:notice] = if @memo.update(memo_params)
                             'メモが編集されました'
                           else
                             'コメントの編集に失敗しました'
                           end
      format.js { render :index }
    end
  end

  def destroy
    @memo.destroy
    respond_to do |format|
      flash.now[:notice] = 'コメントが削除されました'
      format.js { render :index }
    end
  end

  private

  def set_memo
    @memo = Memo.find(params[:id])
  end

  def set_memos
    @memos = Memo.all
  end

  def memo_params
    params.require(:memo).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AjaxTry</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/memos/_edit.html.erb
<%= render 'layouts/flash' %>
<div class="comment_edit_form">
<%= form_with(model: memo, remote: true) do |form| %>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: "memo_description_#{memo.id}" %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
  <%= link_to :back do %>
    戻る
  <% end %>
<% end %>

app/views/memos/_form.html.erb
<%= form_with(model: memo, remote: true) do |form| %>
  <% if memo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(memo.errors.count, "error") %> prohibited this memo from being saved:</h2>

      <ul>
        <% memo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/memos/_index.html.erb
<% memos = @memos.order(created_at: :desc) %>
<%= render 'layouts/flash' %>
<br>
<% memos.each do |memo| %>
  <div id ="this_memo_<%= memo.id %>">
    <span>投稿日時:<%= time_ago_in_words(memo.created_at) %></span>
    <span><%= link_to 'Edit', edit_memo_path(memo), remote: true %></span>
    <span><%= link_to 'Destroy', memo_path(memo.id), method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></span>
    <%= simple_format(memo.content) %>
  </div>
  <hr>
<% end %>

app/views/memos/edit.js.erb
$('.alert').remove();
$("#this_memo_<%= @memo.id %>").replaceWith("<%= j(render 'memos/edit', { memo: @memo }) %>");

app/views/memos/index.html.erb
<h1>Memos</h1>
<%= render 'form', memo: @memo %>
<hr>
<h3>memo list</h3>
<% if @memos != nil %>
  <div id="memos_area">
    <%= render 'memos/index', { memos: @memos } %>
  </div>
<% end %>

app/views/memos/index.js.erb
$("#memos_area").html("<%= j(render 'memos/index', { memos: @memos }) %>")
$("textarea").val('')